### ISSUE TITLE
Pointer

### ISSUE THREAD

**Issue by F-a-y-t-h** [EricBanker12/mhw-fov-changer#5]
MonsterHunterWorld.exe+4EC45A0 > 0x80 > 0x7690 > 0x5f0 is a smaller / more reliable pointer to FOV

-ライトニング

**Comment by EricBanker12** [comment]
You make a good point. I just used the first result I found, but if I switch to the pointer with the fewest jumps, it should be a minor performance improvement.

I even found one that only uses 2 offsets: MonsterHunterWorld.exe+507B8D8 > 0x58 > 0x5F0

I'll plan on picking the pointer with the fewest offsets for the next patch.
